(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('svelte/internal'), require('svelte/internal/disclose-version')) :
  typeof define === 'function' && define.amd ? define(['svelte/internal', 'svelte/internal/disclose-version'], factory) :
  (global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.SvelteComponent = factory(global.internal));
})(this, (function (internal) { 'use strict';

  /* src/Component.svelte generated by Svelte v4.2.19 */

  function create_fragment(ctx) {
  	let h1;

  	return {
  		c() {
  			h1 = internal.element("h1");
  			h1.textContent = `I'm a svelte ${name} component`;
  		},
  		m(target, anchor) {
  			internal.insert(target, h1, anchor);
  		},
  		p: internal.noop,
  		i: internal.noop,
  		o: internal.noop,
  		d(detaching) {
  			if (detaching) {
  				internal.detach(h1);
  			}
  		}
  	};
  }

  let name = "dynamic";

  class Component extends internal.SvelteComponent {
  	constructor(options) {
  		super();
  		internal.init(this, options, null, create_fragment, internal.safe_not_equal, {});
  	}
  }

  // Export the component explicitly
  return Component;

}));
